version: '3'

tasks:
  setup-python:
    desc: Setup Python environment and install dependencies
    dir: python
    cmds:
      - /bin/zsh -c 'rm -rf venv || true'
      - /bin/zsh -c 'python3 -m venv venv'
      - /bin/zsh -c 'source ./venv/bin/activate && pip install -r requirements.txt'
    platforms: [darwin, linux, windows]
    env:
      VIRTUAL_ENV: '{{.USER_WORKING_DIR}}/venv'
      PATH: '{{.USER_WORKING_DIR}}/venv/bin:{{.PATH}}'

  test-python:
    desc: Run Python tests
    dir: python
    cmds:
      - /bin/zsh ./venv/bin/activate && python3 -m pytest numerology_test.py -v
    env:
      VIRTUAL_ENV: '{{.USER_WORKING_DIR}}/venv'
      PATH: '{{.USER_WORKING_DIR}}/venv/bin:{{.PATH}}'

  setup-js:
    desc: Setup JavaScript environment and install dependencies
    dir: js
    cmds:
      - npm install

  test-js:
    desc: Run JavaScript tests
    dir: js
    cmds:
      - npm test

  clean:
    desc: Clean up virtual environments and dependencies
    cmds:
      - rm -rf python/venv
      - rm -rf js/node_modules

  all:
    desc: Setup and test both Python and JavaScript implementations
    cmds:
      - task: setup-python
      - task: test-python
      - task: setup-js
      - task: test-js 